GET http://localhost:3001/api/notas


###  Obtener Nota por ID
GET http://localhost:3001/api/notas/1234


###  Crear Nota
POST http://localhost:3000/api/notas
Content-Type: application/json

{
    "title": "Primer nota creada para mi DB",
    "description": "Descripcion de la primer nota creada para mi d"
}

###  Eliminar Nota
DELETE http://localhost:3001/api/notas/1010

###  Editar Nota
PUT http://localhost:3001/api/notas/1010
Content-Type: application/json

{
    "title": "Nota editada",
    "description": "Descripcion de la nota editada"
}